version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PWD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PWD}"
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  redis:
    image: redis:5.0-alpine
    ports: 
      - "6379:6379"
    depends_on: 
      - db

  app:
    build: .
    volumes:
      - ./src:/awsdescribe
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      SECRET_KEY: "${SECRET_KEY}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PWD: "${DB_PWD}"
      DB_HOST: "${DB_HOST}"
      BROKER_URL: "${BROKER_URL}"
    command: >
      sh -c "python manage.py migrate &&
             supervisord -c ./supervisord.conf"
    depends_on:
      - db
      - redis
