# Generated by Django 3.1 on 2021-01-18 12:20

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_awsdescribe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_groups',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=126, size=6),
        ),
    ]
