# Generated by Django 3.1 on 2021-02-01 01:37

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_awsdescribe', '0002_auto_20210118_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rds',
            fields=[
                ('rds_cluster_resource_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rds_cluster_identifier', models.CharField(max_length=50)),
                ('rds_cluster_status', models.CharField(max_length=10)),
                ('rds_cluster_engine', models.CharField(max_length=30)),
                ('rds_cluster_engineVersion', models.CharField(max_length=30)),
                ('rds_cluster_members', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=126, size=6)),
                ('rds_cluster_update', models.DateTimeField(auto_now=True)),
                ('ae_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_awsdescribe.awsenvironment')),
            ],
        ),
    ]
