# Generated by Django 3.1 on 2021-02-24 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_awsdescribe', '0003_rds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rds',
            name='rds_cluster_engine',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Vpc',
            fields=[
                ('vpc_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vpc_cidrblock', models.CharField(max_length=20)),
                ('vpc_tags', models.TextField()),
                ('vpc_isdefault', models.BooleanField()),
                ('ae_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_awsdescribe.awsenvironment')),
            ],
        ),
    ]
