# Generated by Django 3.1 on 2021-02-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_awsdescribe', '0004_auto_20210224_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rds',
            name='rds_cluster_engine',
            field=models.CharField(max_length=30),
        ),
    ]
