# Generated by Django 3.1 on 2021-03-02 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_awsdescribe', '0005_auto_20210224_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('subnet_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('availability_zone', models.CharField(max_length=50)),
                ('availability_zone_id', models.CharField(max_length=50)),
                ('cidr_block', models.CharField(max_length=20)),
                ('vpc_id', models.CharField(max_length=50)),
                ('assign_ipv6', models.BooleanField()),
                ('subnet_tags', models.TextField()),
                ('ae_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_awsdescribe.awsenvironment')),
            ],
        ),
    ]
