# Generated by Django 3.1 on 2021-03-18 02:28

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_awsdescribe', '0006_subnet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwsenvironmentDetail',
            fields=[
                ('detail_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('detail_use', models.CharField(max_length=30)),
                ('detail_domain', models.CharField(max_length=50)),
                ('detail_account_agency', models.CharField(max_length=20)),
                ('detail_monitoring', models.CharField(max_length=16)),
                ('detail_sre', models.CharField(max_length=20)),
                ('detail_developer', models.CharField(max_length=20)),
                ('detail_product', models.CharField(max_length=30)),
                ('detail_watchman', models.BooleanField()),
                ('detail_vulsan', models.BooleanField()),
                ('detail_os_account_management', django_mysql.models.ListCharField(models.CharField(max_length=16), max_length=51, size=3)),
                ('detail_comment', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='awsenvironment',
            name='ae_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
