# Generated by Django 3.1 on 2021-03-18 09:02

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_awsdescribe', '0007_auto_20210318_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_policies',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), max_length=510, size=10),
        ),
    ]
